# in .cargo/config.toml

[build]
target = "target_os.json"

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[target.'cfg(target_os = "none")']
runner = "bootimage runner"

[test]
Zbuild-std= ["core", "alloc"]
